project_id = "jpndszgkznjmnxldccee"

[functions.meeting-reminders]
verify_jwt = false

[functions.add-friend-from-referral]
verify_jwt = false

[functions.generate-message]
verify_jwt = false

[functions.party-rsvp]
verify_jwt = false

[functions.send-sms-code]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false
